maintainer       "Mark Sonnabaum"
maintainer_email "mark.sonnabaum@acquia.com"
license          "Apache 2.0"
description      "Misc for ci.drush.ws"
version          "0.10.1"
recipe           "ci-drush", "Misc for ci.drush.ws"
